namespace DisplayProfileManager.Services;

/// <summary>Tiny EN/RU string table. Call Loc.SetLocale then Loc.T("key").</summary>
public static class Loc
{
    private static string _locale = "en";
    private static readonly Dictionary<string, (string En, string Ru)> Map = new(StringComparer.OrdinalIgnoreCase)
    {
        ["app.name"] = ("Display Profile Manager", "Display Profile Manager"),
        ["btn.apply"] = ("Apply", "Применить"),
        ["btn.save"] = ("Save", "Сохранить"),
        ["btn.reset.global"] = ("Reset Global defaults", "Сброс Global defaults"),
        ["btn.reset.global.hint"] = ("Rewrites Global defaults to factory values and restores the display. For a quick panic fix use Emergency Restore in the header.", "Перезаписывает Global defaults на заводские и восстанавливает экран. Для быстрого сброса цвета — Emergency Restore в шапке."),
        ["btn.preview"] = ("Preview", "Превью"),
        ["btn.compareAb"] = ("A/B", "A/B"),
        ["btn.scan"] = ("Scan", "Скан"),
        ["btn.addManual"] = ("Add", "Добавить"),
        ["btn.restore"] = ("Restore games", "Восстановить"),
        ["btn.dup"] = ("Duplicate", "Копия"),
        ["btn.delete"] = ("Delete", "Удалить"),
        ["btn.add"] = ("Add", "Добавить"),
        ["btn.settings"] = ("Settings", "Настройки"),
        ["btn.import"] = ("Import…", "Импорт…"),
        ["btn.export"] = ("Export…", "Экспорт…"),
        ["btn.finish"] = ("Finish", "Готово"),
        ["btn.cancel"] = ("Cancel", "Отмена"),
        ["btn.ok"] = ("OK", "OK"),
        ["tab.profiles"] = ("Library", "Библиотека"),
        ["tab.presets"] = ("Presets", "Пресеты"),
        ["tab.global"] = ("Defaults", "Умолчания"),
        ["tab.log"] = ("Log", "Журнал"),
        ["search.placeholder"] = ("Search games…", "Поиск игр…"),
        ["active.none"] = ("No game active", "Игра не активна"),
        ["active.prefix"] = ("Active:", "Активно:"),
        ["tray.open"] = ("Open", "Открыть"),
        ["tray.pause"] = ("Pause monitoring", "Пауза мониторинга"),
        ["tray.resume"] = ("Resume monitoring", "Возобновить"),
        ["tray.reset"] = ("Emergency Restore", "Аварийный сброс"),
        ["tray.overlay"] = ("Live overlay", "Live оверлей"),
        ["tray.exit"] = ("Exit", "Выход"),
        ["tray.presets"] = ("Presets", "Пресеты"),
        ["tray.none"] = ("(no active game)", "(нет активной игры)"),
        ["tray.profiles"] = ("Profiles", "Профили"),
        ["tray.profiles.none"] = ("(no enabled profiles)", "(нет активных профилей)"),
        ["tray.hotkeys"] = ("Hotkeys", "Горячие клавиши"),
        ["tray.hotkeys.none"] = ("(none set)", "(не заданы)"),
        ["tray.hotkeys.copied"] = ("Hotkey copied", "Горячая клавиша скопирована"),
        ["tray.hotkeys.toggleOverlay"] = ("Toggle overlay", "Оверлей"),
        ["tray.hotkeys.emergencyRestore"] = ("Emergency restore", "Аварийный сброс"),
        ["tray.hotkeys.nextPreset"] = ("Next preset", "След. пресет"),
        ["tray.hotkeys.previousPreset"] = ("Previous preset", "Пред. пресет"),
        ["tray.hotkeys.compareAb"] = ("A/B compare", "A/B сравнение"),
        ["setup.title"] = ("Welcome", "Добро пожаловать"),
        ["setup.subtitle"] = ("Quick setup — you can change this later in Settings.", "Быстрая настройка — потом можно изменить в Параметрах."),
        ["setup.tips"] = ("After setup: use the Play tab for live color while gaming, Presets for hotkey profiles, and Pack gallery for ready-made Tarkov / Valorant / PUBG packs.", "После настройки: вкладка Play — live-цвет в игре, Presets — хоткеи, Pack gallery — готовые паки Tarkov / Valorant / PUBG."),
        ["setup.language"] = ("Language", "Язык"),
        ["setup.theme"] = ("Theme", "Тема"),
        ["setup.theme.dark"] = ("Dark", "Тёмная"),
        ["setup.theme.light"] = ("Light", "Светлая"),
        ["setup.theme.custom"] = ("Custom", "Своя"),
        ["setup.editPalette"] = ("Edit palette…", "Настроить палитру…"),
        ["setup.autostart"] = ("Start with Windows", "Запуск с Windows"),
        ["setup.startMin"] = ("Start minimized to tray", "Сразу в трей"),
        ["setup.notify"] = ("Toast when a game starts", "Уведомление при старте игры"),
        ["setup.backup"] = ("Backup config before each save", "Бэкап конфига перед сохранением"),
        ["setup.trayClose"] = ("Close window → stay in tray", "Закрытие окна → остаться в трее"),
        ["setup.monitor"] = ("Default monitor for resolution", "Монитор для разрешения"),
        ["setup.monitor.primary"] = ("Primary", "Основной"),
        ["settings.title"] = ("Settings", "Параметры"),
        ["settings.appearance"] = ("Appearance", "Внешний вид"),
        ["settings.behavior"] = ("Behavior", "Поведение"),
        ["settings.data"] = ("Data", "Данные"),
        ["settings.sound"] = ("Sound", "Звук"),
        ["settings.sound.enable"] = ("UI sounds", "Звуки интерфейса"),
        ["settings.sound.volume"] = ("Volume", "Громкость"),
        ["settings.sound.preview"] = ("Preview chime", "Прослушать"),
        ["settings.sound.preview.btn"] = ("Preview", "Прослушать"),
        ["settings.sound.muteInGame"] = ("Mute UI sounds while a game is active", "Отключать звуки интерфейса во время игры"),
        ["sound.cat.open"] = ("Open", "Открытие"),
        ["sound.cat.click"] = ("Click", "Клик"),
        ["sound.cat.save"] = ("Save", "Сохранение"),
        ["sound.cat.launch"] = ("Launch", "Запуск"),
        ["sound.cat.done"] = ("Done", "Готово"),
        ["sound.cat.empty"] = ("Empty", "Пусто"),
        ["sound.cat.armed"] = ("Armed", "Профиль активен"),
        ["sound.cat.warn"] = ("Warn", "Предупреждение"),
        ["sound.cat.error"] = ("Error", "Ошибка"),
        ["sound.cat.preset"] = ("Preset applied", "Пресет применён"),
        ["settings.confirmDelete"] = ("Confirm before delete", "Подтверждать удаление"),
        ["settings.showActive"] = ("Show active profile in header", "Показывать активный профиль в шапке"),
        ["toast.game"] = ("Profile applied", "Профиль применён"),
        ["toast.color"] = ("Color: {0}", "Цвет: {0}"),
        ["tray.idle"] = ("DPM — idle", "DPM — ожидание"),
        ["toast.snapshot"] = ("Snapshot saved", "Снимок сохранён"),
        ["toast.emergency"] = ("Emergency Restore done", "Аварийный сброс выполнен"),
        ["toast.config.recovered"] = ("Config recovered", "Конфиг восстановлен"),
        ["toast.preview"] = ("Color preview applied — use A/B to compare with factory", "Превью цвета — A/B сравнивает с заводским"),
        ["toast.ab.preview"] = ("A/B: Preview", "A/B: Превью"),
        ["toast.ab.factory"] = ("A/B: Factory", "A/B: Заводской"),
        ["toast.crash.restored"] = ("Restored after crash", "Восстановлено после сбоя"),
        ["toast.health"] = ("GPU: {0}", "GPU: {0}"),
        ["toast.imported"] = ("Profiles imported", "Профили импортированы"),
        ["toast.exported"] = ("Profiles exported", "Профили экспортированы"),
        ["toast.saved"] = ("Saved", "Сохранено"),
        ["confirm.delete"] = ("Delete this profile?", "Удалить этот профиль?"),
        ["hotkey.compareAb"] = ("A/B compare", "Сравнить A/B"),
        ["hotkey.zoom"] = ("Toggle zoom", "Приближение"),
        ["hotkey.overlay"] = ("Toggle overlay", "Оверлей"),
        ["hotkey.emergency"] = ("Emergency Restore", "Аварийный сброс"),
        ["hotkey.app"] = ("App hotkeys", "Горячие клавиши"),
        ["status.monitoring"] = ("Monitoring", "Мониторинг"),
        ["log.refresh"] = ("Refresh", "Обновить"),
        ["log.openFolder"] = ("Open log", "Открыть лог"),
        ["zoom.factor"] = ("Zoom factor", "Кратность зума"),
        ["zoom.hint"] = ("Zooms the center of the desktop via Windows Magnifier API — no injection into games.", "Приближает центр экрана через Windows Magnifier API — без инжекта в игры."),
        ["toast.zoom.on"] = ("Zoom ×{0} on", "Зум ×{0} вкл"),
        ["toast.zoom.off"] = ("Zoom off", "Зум выкл"),
        ["toast.zoom.unavailable"] = ("Zoom unavailable on this system", "Зум недоступен на этой системе"),
        ["about.title"] = ("About", "О программе"),
        ["about.creator"] = ("Created by Nakidev", "Создатель: Nakidev"),
        ["about.contacts"] = ("Discord & Telegram: @nakidev", "Discord и Telegram: @nakidev"),
        ["about.site"] = ("github.com/Naki-404/DisplayProfileManager", "github.com/Naki-404/DisplayProfileManager"),
        ["toast.hotkey.busy"] = ("Hotkey busy: {0}", "Хоткей занят: {0}"),
        ["toast.hotkey.failed"] = ("{0} hotkeys failed (in use?)", "{0} хоткеев не зарегистрированы"),
        ["display"] = ("Display", "Дисплей"),
        ["alreadyRunning"] = ("Display Profile Manager is already running.", "Display Profile Manager уже запущен."),

        // Profile editor / color
        ["color.backend"] = ("Color backend", "Способ цвета"),
        ["color.lock"] = ("Lock color while game is running", "Удерживать цвет, пока игра запущена"),
        ["color.lock.tip"] = ("Re-applies gamma every 0.5–2s so the game cannot reset it.", "Периодически заново ставит гамму, чтобы игра её не сбрасывала."),
        ["color.backend.tip"] = (
            "Left: NVIDIA/AMD Control Panel–style B/C/G + Digital Vibrance. Right: Low Level — full RivaTuner B/C/G ramp.",
            "Слева: B/C/G как в панели NVIDIA/AMD + Digital Vibrance. Справа: Low Level — полная рампа RivaTuner B/C/G."),
        ["color.apply"] = ("Apply color with this profile", "Применять цвет с этим профилем"),
        ["color.apply.tip"] = ("When enabled, brightness / contrast / gamma / vibrance from this profile are applied when the game starts.", "Если включено, яркость / контраст / гамма / vibrance из профиля применяются при старте игры."),
        ["color.brightness.tip"] = ("RivaTuner Brightness (−125..125). Added in 8-bit space before contrast/gamma.", "Яркость RivaTuner (−125..125). Добавляется в 8-битном пространстве до контраста/гаммы."),
        ["color.vibrance.tip"] = ("Color saturation. On NVIDIA/AMD uses driver vibrance; ignored by the Low Level ramp.", "Насыщенность. На NVIDIA/AMD — vibrance драйвера; на рампу Low Level не влияет."),
        ["color.shadow.tip"] = ("Shadow Boost (0–100): lifts dark areas while preserving highlights. Low Level only.", "Shadow Boost (0–100): поднимает тени, сохраняя света. Только Low Level."),
        ["restore.mode.tip"] = ("What to restore when this game exits: previous PC snapshot, Global Defaults, or leave as-is.", "Что восстановить при выходе из игры: снимок ПК, Global Defaults, или ничего."),
        ["restore.mode.lbl"] = ("On game exit", "При выходе из игры"),
        ["btn.emergency"] = ("Emergency Restore", "Аварийный сброс"),
        ["btn.emergency.short"] = ("Reset display", "Сброс экрана"),
        ["btn.emergency.tip"] = ("Restores display, color, power, and session settings to a safe state.", "Восстанавливает дисплей, цвет, питание и сессию в безопасное состояние."),
        ["display.res.tip"] = ("Switch the selected monitor to this resolution while the game runs, then restore on exit.", "Переключает выбранный монитор на это разрешение на время игры и возвращает назад при выходе."),
        ["display.power.tip"] = ("Switch Windows power plan (High performance / Balanced) while the game runs.", "Переключает схему электропитания Windows (высокая производительность / сбалансированная) на время игры."),
        ["companions.tip"] = ("Extra programs launched with the game (optional args, e.g. Overwolf -launchapp …). Closed when the game exits if configured.", "Доп. программы при старте игры (можно указать аргументы, напр. Overwolf -launchapp …). При выходе могут закрываться."),
        ["btn.apply.tip"] = ("Apply to the display for the current tab. Settings autosave as you edit — no Save button.", "Применить к экрану для текущей вкладки. Настройки сохраняются сами при изменении — кнопки Save нет."),
        ["toast.applied"] = ("Applied", "Применено"),
        ["toast.preset.hotkey"] = ("Preset hotkey applied", "Пресет по хоткею применён"),
        ["toast.global.kept.preset"] = ("Global saved — active preset kept on screen", "Global сохранён — активный пресет на экране не тронут"),
        ["overlay.title"] = ("Live color", "Цвет live"),
        ["overlay.live.hint"] = ("Sliders apply to the display instantly — no Save needed.", "Ползунки сразу меняют картинку на экране."),
        ["overlay.apply"] = ("Save", "Сохранить"),
        ["overlay.more"] = ("More", "Ещё"),
        ["overlay.save.preset"] = ("Save as Preset", "Как пресет"),
        ["overlay.update.preset"] = ("Update Preset", "Обновить пресет"),
        ["overlay.reset"] = ("Reset", "Сброс"),
        ["overlay.emergency"] = ("Emergency", "Авария"),
        ["overlay.preset"] = ("Preset: {0}", "Пресет: {0}"),
        ["overlay.preset.name"] = ("Preset name", "Имя пресета"),
        ["overlay.need.profile"] = ("Select or start a game profile first.", "Сначала выберите или запустите профиль игры."),
        ["overlay.need.preset"] = ("Create a color preset for this game first.", "Сначала создайте цветовой пресет для этой игры."),
        ["overlay.collapse"] = ("Minimize to pill", "Свернуть в таб"),
        ["overlay.hide"] = ("Hide overlay", "Скрыть оверлей"),
        ["overlay.mini"] = ("DPM", "DPM"),
        ["overlay.no.game"] = ("No active game — preview only", "Нет активной игры — только превью"),
        ["overlay.open"] = ("Live overlay", "Live оверлей"),
        ["overlay.auto"] = ("Show overlay when a game starts", "Показывать оверлей при старте игры"),
        ["overlay.auto.hint"] = ("Compact topmost panel with live color sliders over the game.", "Компактная панель поверх игры с live-ползунками цвета."),
        ["overlay.panelOpacity"] = ("Panel opacity", "Прозрачность панели"),
        ["overlay.applied"] = ("Color saved", "Цвет сохранён"),
        ["btn.overlay"] = ("Live overlay", "Live оверлей"),
        ["btn.overlay.tip"] = ("Floating panel over the game — sliders apply color live. Main window hides to tray until you close the overlay.", "Панель поверх игры — ползунки сразу меняют цвет. Главное окно уходит в трей, пока оверлей открыт."),
        ["presets.export.tip"] = ("Share this game’s preset pack as a file others can import.", "Сохранить набор пресетов этой игры в файл для передачи."),
        ["presets.import.tip"] = ("Load a preset pack file into the selected game.", "Загрузить файл с пресетами в выбранную игру."),
        ["global.autostart.tip"] = ("Create a scheduled task so the app starts when you sign in to Windows.", "Создаёт задачу планировщика, чтобы приложение запускалось при входе в Windows."),
        ["global.startmin.tip"] = ("Start hidden in the system tray instead of showing the main window.", "Запускать свёрнутым в трей, без показа главного окна."),

        // Session extras
        ["session.title"] = ("Session extras", "Дополнительно на сессию"),
        ["session.sub"] = ("System-only tweaks (no game injection)", "Только системные настройки (без вмешательства в игру)"),
        ["session.deferred"] = ("Deferred re-apply: {0} s", "Повторное применение через: {0} с"),
        ["session.deferred.tip"] = ("Wait N seconds after game start, then apply display/color again. Helps when a launcher overwrites settings.", "Подождать N секунд после старта игры и снова применить цвет/разрешение. Полезно, если лаунчер перебивает настройки."),
        ["session.quiet"] = ("Quiet notifications", "Тихие уведомления"),
        ["session.quiet.tip"] = ("Turns off Windows toast notifications while the game runs (Focus Assist–style). Restored when the game exits.", "Отключает всплывающие уведомления Windows на время игры (как Focus Assist). После выхода из игры возвращает обратно."),
        ["session.night"] = ("Disable Night Light", "Отключить Night Light"),
        ["session.night.tip"] = ("Best-effort one-way off (Windows does not expose a reliable read). Will not auto-re-enable on game exit.", "Одностороннее выключение (Windows не даёт надёжно прочитать состояние). При выходе из игры само не включится."),
        ["session.hdr"] = ("Disable Auto HDR", "Отключить Auto HDR"),
        ["session.hdr.tip"] = ("Turns off Windows Auto HDR for games so SDR color presets are not altered.", "Отключает Auto HDR Windows для игр, чтобы SDR-пресеты цвета не искажались."),
        ["session.primary"] = ("Primary monitor only", "Только основной монитор"),
        ["session.primary.tip"] = ("Temporarily disables extra monitors while the game runs. Restored on exit.", "Временно отключает дополнительные мониторы на время игры. После выхода восстанавливает."),
        ["session.bright"] = ("Set monitor brightness (DDC/CI)", "Яркость монитора (DDC/CI)"),
        ["session.bright.lbl"] = ("Panel brightness: {0}%", "Яркость панели: {0}%"),
        ["session.bright.tip"] = ("Changes the monitor’s own backlight via DDC/CI (not gamma). Needs a compatible cable/monitor.", "Меняет подсветку самого монитора через DDC/CI (не гамму). Нужен поддерживаемый монитор/кабель."),
        ["session.audio"] = ("Switch default audio device", "Сменить устройство звука"),
        ["session.audio.tip"] = ("Switches the Windows default playback device for this profile (e.g. headset). Restored on exit.", "Переключает устройство воспроизведения Windows по умолчанию (например наушники). После выхода возвращает."),
        ["session.scaling"] = ("Scaling mode", "Масштабирование"),
        ["session.scaling.tip"] = ("How a non-native resolution is shown: default, stretch, or center (letterbox).", "Как показывать неродное разрешение: по умолчанию, растянуть или по центру."),
        ["presets.export"] = ("Export", "Экспорт"),
        ["presets.import"] = ("Import", "Импорт"),
        ["presets.gallery"] = ("Pack gallery", "Галерея паков"),
        ["presets.gallery.hint"] = ("Apply a built-in pack to the game selected on the Presets tab.", "Применить встроенный пак к игре, выбранной на вкладке Пресетов."),
        ["presets.empty"] = ("No presets yet — add one or open the pack gallery.", "Пресеттов пока нет — добавьте или откройте галерею паков."),
        ["presets.empty.gallery"] = ("Open pack gallery", "Открыть галерею паков"),
        ["presets.pick.game"] = ("Select a game on the Presets tab first.", "Сначала выберите игру на вкладке Пресетов."),
        ["pack.tarkov"] = ("Tarkov Riva presets", "Tarkov — пресеты Riva"),
        ["pack.tarkov.sub"] = ("gamma-1 / gamma-2 / Night / Neutral", "gamma-1 / gamma-2 / Night / Neutral"),
        ["pack.valorant"] = ("Valorant stretch", "Valorant stretch"),
        ["pack.valorant.sub"] = ("Stretch resolutions + Vibrance+", "Stretch-разрешения + Vibrance+"),
        ["pack.pubg"] = ("PUBG stretch", "PUBG stretch"),
        ["pack.pubg.sub"] = ("2560×1440 / 1920×1080 stretch helpers", "Помощники stretch 2560×1440 / 1920×1080"),
        ["pack.appliesTo"] = ("Applies to: {0}", "Применится к: {0}"),
        ["profile.export"] = ("Export", "Экспорт"),
        ["profile.import"] = ("Import", "Импорт"),
        ["profile.pick"] = ("Select a profile first.", "Сначала выберите профиль."),
        ["profile.startup"] = ("Startup preset", "Пресет при старте"),
        ["profile.startup.none"] = ("(none)", "(нет)"),
        ["profile.aliases"] = ("Process aliases (comma-separated)", "Алиасы процессов (через запятую)"),
        ["profile.delay"] = ("Apply delay: {0} s", "Задержка применения: {0} с"),
        ["profile.focus"] = ("Wait for game window focus", "Ждать фокуса окна игры"),
        ["profile.softAltTab"] = ("Soft restore on Alt-Tab", "Мягкий возврат при Alt-Tab"),
        ["profile.softAltTab.tip"] = ("When you Alt-Tab out of the game, desktop color/resolution is softly restored, then re-applied when focus returns — companions keep running.", "При переключении из игры (Alt-Tab) цвет/разрешение рабочего стола мягко восстанавливаются и снова применяются при возврате фокуса — компаньоны не останавливаются."),
        ["profile.fpsLimit"] = ("FPS limit (NVIDIA only)", "Лимит FPS (только NVIDIA)"),
        ["profile.fpsLimit.tip"] = ("Caps this game's frame rate via the NVIDIA driver (DRS). 0 / off = no cap.", "Ограничивает FPS игры через драйвер NVIDIA (DRS). 0 / выкл = без ограничения."),
        ["profile.fpsLimit.hint"] = ("Requires an NVIDIA GPU (driver DRS) — hidden/no-op otherwise.", "Нужен GPU NVIDIA (драйвер DRS) — иначе не действует."),
        ["profile.fpsLimit.unavailable"] = ("NVIDIA driver settings not detected — FPS limit will have no effect.", "Настройки драйвера NVIDIA не найдены — лимит FPS не подействует."),
        ["display.refresh"] = ("Refresh rate", "Частота обновления"),
        ["display.refresh.none"] = ("(don't change)", "(не менять)"),
        ["session.layout"] = ("Monitor layout", "Раскладка мониторов"),
        ["session.templates"] = ("Templates", "Шаблоны"),
        ["session.tpl.competitive"] = ("Competitive", "Соревновательный"),
        ["session.tpl.immersive"] = ("Immersive", "Иммерсивный"),
        ["session.tpl.minimal"] = ("Minimal", "Минимальный"),
        ["hotkey.next"] = ("Next preset", "Следующий пресет"),
        ["hotkey.prev"] = ("Previous preset", "Предыдущий пресет"),
        ["hotkey.hint"] = ("Click a field and press a key (modifiers optional). Esc / Backspace / Delete or Clear removes it. Per-preset binds are on the Presets tab.", "Кликните поле и нажмите клавишу (модификаторы необязательны). Esc / Backspace / Delete или Clear снимает привязку. Хоткеи пресетов — на вкладке Пресетов."),
        ["hotkey.conflict"] = ("Hotkey conflict: {0}", "Конфликт хоткея: {0}"),
        ["overlay.hotkeyOnly"] = ("Hotkey-only overlay (compact pill)", "Оверлей только хоткеем (компактная таблетка)"),
        ["overlay.lock"] = ("Lock color while game running", "Удерживать цвет, пока игра запущена"),
        ["toast.profile.exported"] = ("Profile exported", "Профиль экспортирован"),
        ["toast.profile.imported"] = ("Profile imported", "Профиль импортирован"),
        ["toast.pack.applied"] = ("Pack applied: {0}", "Пак применён: {0}"),
        ["toast.session.template"] = ("Session template applied", "Шаблон сессии применён"),
        ["toast.hotkey.next"] = ("Next preset", "Следующий пресет"),
        ["toast.hotkey.prev"] = ("Previous preset", "Предыдущий пресет"),
        ["toast.hotkey.ab"] = ("A/B compare", "Сравнение A/B"),
        ["unsaved.title"] = ("Unsaved changes", "Несохранённые изменения"),
        ["unsaved.message"] = ("You have unsaved changes. Save them before continuing?", "Есть несохранённые изменения. Сохранить перед продолжением?"),
        ["unsaved.save"] = ("Save", "Сохранить"),
        ["unsaved.discard"] = ("Don't save", "Не сохранять"),
        ["unsaved.cancel"] = ("Cancel", "Отмена"),
        ["btn.openPresets"] = ("Open Presets", "Открыть пресеты"),
        ["color.summary.default"] = ("Configure color on the Presets tab (startup preset applied on game start).", "Настройте цвет на вкладке Пресетов (пресет при старте применяется при запуске игры)."),
        ["color.summary.none"] = ("No startup preset — configure one on the Presets tab.", "Нет пресета при старте — настройте его на вкладке Пресетов."),
        ["dirty.unsaved"] = ("Unsaved changes", "Несохранённые изменения"),
        ["session.advanced"] = ("Advanced session", "Дополнительно на сессию"),
        ["profile.advanced"] = ("Advanced", "Дополнительно"),
        ["play.session"] = ("Session options", "Параметры сессии"),
        ["hotkey.cheatsheet"] = ("Cheat sheet: hotkeys work while their game (or preset game) is active. Clear a field to remove a binding.", "Шпаргалка: хоткеи работают, пока активна их игра (или выбранная игра пресетов). Очистите поле, чтобы снять привязку."),

        // Play tab
        ["tab.play"] = ("Play", "Игра"),
        ["play.title"] = ("Now playing", "Сейчас играем"),
        ["play.noGame"] = ("No game selected", "Игра не выбрана"),
        ["play.status.active"] = ("Active", "Активна"),
        ["play.status.idle"] = ("Idle", "Ожидание"),
        ["play.color"] = ("Live color", "Цвет live"),
        ["play.color.hint"] = ("Sliders apply instantly. Pick a preset chip to edit it live, or Live for a one-off preview.", "Ползунки применяются сразу. Выберите пресет, чтобы редактировать его live, или Live для разового превью."),
        ["play.presets"] = ("Presets", "Пресеты"),
        ["play.liveChip"] = ("Live", "Live"),
        ["play.hotkeys"] = ("Hotkeys", "Хоткеи"),
        ["play.hotkeys.none"] = ("No hotkeys configured yet.", "Хоткеи ещё не настроены."),
        ["btn.launchGame"] = ("Launch game", "Запустить игру"),
    };

    public static string Locale => _locale;

    public static event Action? Changed;

    public static void SetLocale(string? locale)
    {
        var next = string.Equals(locale, "ru", StringComparison.OrdinalIgnoreCase) ? "ru" : "en";
        bool changed = _locale != next;
        _locale = next;
        if (changed)
            Changed?.Invoke();
    }

    /// <summary>Format Loc.T key that contains {0} placeholders.</summary>
    public static string Tf(string key, params object[] args)
    {
        try { return string.Format(T(key), args); }
        catch { return T(key); }
    }

    public static string T(string key)
    {
        if (!Map.TryGetValue(key, out var pair)) return key;
        return _locale == "ru" ? pair.Ru : pair.En;
    }
}
